services:
  postgres:
    image: postgres
    container_name: postgres-ssmup
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ssmup
      POSTGRES_PASSWORD: 123456 # Senha do usu√°rio
      POSTGRES_DB: ssmup

  redis:
    image: redis:8.4-alpine
    container_name: redis-ssmup
    depends_on:
      - postgres
    ports:
      - "6379:6379"
    restart: always

  api:
    build: .
    container_name: api-ssmup
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ssmup
      - DB_USER=ssmup
      - DB_PASSWORD=123456